/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author centr
 */
public class Factura extends javax.swing.JApplet {

    /**
     * Initializes the applet Factura
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextProducto1 = new javax.swing.JTextField();
        TextProducto2 = new javax.swing.JTextField();
        TextProducto3 = new javax.swing.JTextField();
        TextProducto4 = new javax.swing.JTextField();
        TextProducto5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextValUnita1 = new javax.swing.JTextField();
        TextValUnita2 = new javax.swing.JTextField();
        TextValUnita3 = new javax.swing.JTextField();
        TextValUnita4 = new javax.swing.JTextField();
        TextValUnita5 = new javax.swing.JTextField();
        Cantidad = new javax.swing.JLabel();
        TextCantidad1 = new javax.swing.JTextField();
        TextCantidad2 = new javax.swing.JTextField();
        TextCantidad3 = new javax.swing.JTextField();
        TextCantidad4 = new javax.swing.JTextField();
        TextCantidad5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextVlrTotal1 = new javax.swing.JTextField();
        TextVlrTotal2 = new javax.swing.JTextField();
        TextVlrTotal3 = new javax.swing.JTextField();
        TextVlrTotal4 = new javax.swing.JTextField();
        TextVlrTotal5 = new javax.swing.JTextField();
        BtnCalcular = new javax.swing.JToggleButton();
        BtnNuevo = new javax.swing.JToggleButton();
        TextSalida = new javax.swing.JTextField();
        TextTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dyd = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ORDEN DE COMPRA");

        jLabel2.setText("Cliente");

        TextCliente.setFocusCycleRoot(true);

        jLabel3.setText("Prodcucto");
        jLabel3.setToolTipText("");

        jLabel4.setText("Vlr. Unitario");
        jLabel4.setToolTipText("");

        Cantidad.setText("Cantidad");

        TextCantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCantidad1ActionPerformed(evt);
            }
        });

        TextCantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCantidad2ActionPerformed(evt);
            }
        });

        TextCantidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCantidad3ActionPerformed(evt);
            }
        });

        TextCantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCantidad4ActionPerformed(evt);
            }
        });

        TextCantidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCantidad5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Vlr. Total");

        TextVlrTotal1.setEnabled(false);
        TextVlrTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextVlrTotal1ActionPerformed(evt);
            }
        });

        TextVlrTotal2.setEnabled(false);
        TextVlrTotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextVlrTotal2ActionPerformed(evt);
            }
        });

        TextVlrTotal3.setEnabled(false);
        TextVlrTotal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextVlrTotal3ActionPerformed(evt);
            }
        });

        TextVlrTotal4.setEnabled(false);
        TextVlrTotal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextVlrTotal4ActionPerformed(evt);
            }
        });

        TextVlrTotal5.setEnabled(false);
        TextVlrTotal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextVlrTotal5ActionPerformed(evt);
            }
        });

        BtnCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCalcular.setText("CALCULAR");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        BtnNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnNuevo.setText("NUEVO CALCULAR");
        BtnNuevo.setHideActionText(true);
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        TextSalida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextSalida.setEnabled(false);
        TextSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSalidaActionPerformed(evt);
            }
        });

        TextTotal.setEnabled(false);

        jLabel6.setText("Valor Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextValUnita3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextValUnita4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextValUnita5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnCalcular))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(BtnNuevo))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(TextProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TextProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(44, 44, 44)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(TextValUnita1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TextValUnita2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(46, 46, 46)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(TextCantidad1))
                                                .addComponent(TextCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 34, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextVlrTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addComponent(TextVlrTotal1)
                                        .addComponent(TextVlrTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(TextVlrTotal4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(TextVlrTotal5, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(TextTotal)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(40, 40, 40)
                                    .addComponent(TextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(TextSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dyd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(Cantidad)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextValUnita1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextVlrTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextValUnita2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextVlrTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextValUnita3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextVlrTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextValUnita4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextVlrTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextValUnita5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextVlrTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCalcular)
                    .addComponent(BtnNuevo))
                .addGap(35, 35, 35)
                .addComponent(TextSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(dyd, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextCantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCantidad1ActionPerformed

    private void TextCantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCantidad2ActionPerformed

    private void TextCantidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCantidad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCantidad3ActionPerformed

    private void TextCantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCantidad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCantidad4ActionPerformed

    private void TextCantidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCantidad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCantidad5ActionPerformed

    private void TextVlrTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextVlrTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextVlrTotal1ActionPerformed

    private void TextVlrTotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextVlrTotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextVlrTotal2ActionPerformed

    private void TextVlrTotal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextVlrTotal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextVlrTotal3ActionPerformed

    private void TextVlrTotal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextVlrTotal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextVlrTotal4ActionPerformed

    private void TextVlrTotal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextVlrTotal5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextVlrTotal5ActionPerformed

    private void TextSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSalidaActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        double Vunitario1 = Double.parseDouble(TextValUnita1.getText());
        double Vunitario2 = Double.parseDouble(TextValUnita2.getText());        
        double Vunitario3 = Double.parseDouble(TextValUnita3.getText());
        double Vunitario4 = Double.parseDouble(TextValUnita4.getText());
        double Vunitario5 = Double.parseDouble(TextValUnita5.getText());
        
        double cantidad1 = Double.parseDouble(TextCantidad1.getText());        
        double cantidad2 = Double.parseDouble(TextCantidad2.getText());        
        double cantidad3 = Double.parseDouble(TextCantidad3.getText());        
        double cantidad4 = Double.parseDouble(TextCantidad4.getText());        
        double cantidad5 = Double.parseDouble(TextCantidad5.getText());

        double resul1= Vunitario1 * cantidad1;       
        double resul2= Vunitario2 * cantidad2;        
        double resul3= Vunitario3 * cantidad3;        
        double resul4= Vunitario4 * cantidad4;       
        double resul5= Vunitario5 * cantidad5;
        
        
        double sumatoria= resul1 + resul2 +resul3 + resul4 + resul5;
        
        TextVlrTotal1.setText(""+ resul1);        
        TextVlrTotal2.setText(""+ resul2);
        TextVlrTotal3.setText(""+ resul3);        
        TextVlrTotal4.setText(""+ resul4);        
        TextVlrTotal5.setText(""+ resul5);
        
        TextTotal.setText(""+ sumatoria);       
        
        TextSalida.setText( "  "+ TextCliente.getText() + ".  El total de su compra fue : "+ sumatoria);

dyd.setText("©D&D");
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        TextVlrTotal1.setText("");        
        TextVlrTotal2.setText("");
        TextVlrTotal3.setText("");        
        TextVlrTotal4.setText("");        
        TextVlrTotal5.setText("");
        
        TextValUnita1.setText("");        
        TextValUnita2.setText("");
        TextValUnita3.setText("");        
        TextValUnita4.setText("");        
        TextValUnita5.setText("");
        
        TextCantidad1.setText("");        
        TextCantidad2.setText("");
        TextCantidad3.setText("");        
        TextCantidad4.setText("");        
        TextCantidad5.setText("");
        
        TextProducto1.setText("");
        TextProducto2.setText("");
        TextProducto3.setText("");
        TextProducto4.setText("");
        TextProducto5.setText("");
        
        TextTotal.setText("");       
        
        TextSalida.setText("");       
        
        TextCliente.setText("");

    }//GEN-LAST:event_BtnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnCalcular;
    private javax.swing.JToggleButton BtnNuevo;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JTextField TextCantidad1;
    private javax.swing.JTextField TextCantidad2;
    private javax.swing.JTextField TextCantidad3;
    private javax.swing.JTextField TextCantidad4;
    private javax.swing.JTextField TextCantidad5;
    private javax.swing.JTextField TextCliente;
    private javax.swing.JTextField TextProducto1;
    private javax.swing.JTextField TextProducto2;
    private javax.swing.JTextField TextProducto3;
    private javax.swing.JTextField TextProducto4;
    private javax.swing.JTextField TextProducto5;
    private javax.swing.JTextField TextSalida;
    private javax.swing.JTextField TextTotal;
    private javax.swing.JTextField TextValUnita1;
    private javax.swing.JTextField TextValUnita2;
    private javax.swing.JTextField TextValUnita3;
    private javax.swing.JTextField TextValUnita4;
    private javax.swing.JTextField TextValUnita5;
    private javax.swing.JTextField TextVlrTotal1;
    private javax.swing.JTextField TextVlrTotal2;
    private javax.swing.JTextField TextVlrTotal3;
    private javax.swing.JTextField TextVlrTotal4;
    private javax.swing.JTextField TextVlrTotal5;
    private javax.swing.JLabel dyd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
